name: Vercel Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Ensure vercel.json has a blank line
        run: |
          if [ -f vercel.json ]; then
            if [ -z "$(tail -c 1 vercel.json)" ]; then
              echo "vercel.json already ends with a blank line."
            else
              echo "" >> vercel.json
              echo "Added a blank line to vercel.json."
            fi
          else
            echo "vercel.json not found, exiting..."
            exit 1
          fi

      - name: Check for Changes
        id: git-check
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "push_needed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "push_needed=true" >> $GITHUB_ENV
          fi

      - name: Configure Git
        if: env.push_needed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        if: env.push_needed == 'true'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add vercel.json
          git commit -m "Ensure vercel.json has a blank line"
          git push origin ${{ github.event.inputs.branch }}

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --branch ${{ github.event.inputs.branch }}
